/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AreaMembrosRouteImport } from './routes/area-membros'
import { Route as ApiPublicOmegapayWebhookRouteImport } from './routes/api/public/omegapay-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaMembrosRoute = AreaMembrosRouteImport.update({
  id: '/area-membros',
  path: '/area-membros',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOmegapayWebhookRoute =
  ApiPublicOmegapayWebhookRouteImport.update({
    id: '/api/public/omegapay-webhook',
    path: '/api/public/omegapay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/area-membros': typeof AreaMembrosRoute
  '/api/public/omegapay-webhook': typeof ApiPublicOmegapayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/area-membros': typeof AreaMembrosRoute
  '/api/public/omegapay-webhook': typeof ApiPublicOmegapayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/area-membros': typeof AreaMembrosRoute
  '/api/public/omegapay-webhook': typeof ApiPublicOmegapayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/area-membros' | '/api/public/omegapay-webhook'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/area-membros' | '/api/public/omegapay-webhook'
  id: '__root__' | '/' | '/area-membros' | '/api/public/omegapay-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreaMembrosRoute: typeof AreaMembrosRoute
  ApiPublicOmegapayWebhookRoute: typeof ApiPublicOmegapayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area-membros': {
      id: '/area-membros'
      path: '/area-membros'
      fullPath: '/area-membros'
      preLoaderRoute: typeof AreaMembrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/omegapay-webhook': {
      id: '/api/public/omegapay-webhook'
      path: '/api/public/omegapay-webhook'
      fullPath: '/api/public/omegapay-webhook'
      preLoaderRoute: typeof ApiPublicOmegapayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreaMembrosRoute: AreaMembrosRoute,
  ApiPublicOmegapayWebhookRoute: ApiPublicOmegapayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
